const categorySchema = {
  $schema: "http://json-schema.org/draft-07/schema#",
  type: "object",
  properties: {
    PartitionKey: {
      type: "string",
      description: "The category name",
    },
    RowKey: {
      type: "string",
      description: "Unique index value starting at 0 and increasing by 1",
    },
    Timestamp: {
      type: "string",
      description: "Timestamp auto generated by azure",
    },
    Generic1: {
      type: "string",
      description: "First generic rating name i.e. 'Food Rating'",
    },
    Generic2: {
      type: "string",
      description: "Second generic rating name i.e. 'Ambience Rating'",
    },
    Special: {
      type: "string",
      description:
        "Rating that is specific to the category & will have seperate Stephen & Sans ratings",
    },
  },
  required: ["PartitionKey", "RowKey", "Special"],
  additionalProperties: false,
};

const locationSchema = {
  $schema: "http://json-schema.org/draft-07/schema#",
  type: "object",
  properties: {
    PartitionKey: {
      type: "string",
      description: "The category name",
    },
    RowKey: {
      type: "string",
      description: "Unique index value starting at 0 and increasing by 1",
    },
    Timestamp: {
      type: "string",
      description: "Timestamp auto generated by azure",
    },
    Name: {
      type: "string",
      description: "Name of the location",
    },
    Latitude: {
      type: "number",
      description: "Latitude coordinate of the location pin",
      minimum: -90,
      maximum: 90,
    },
    Longitude: {
      type: "number",
      description: "Longitude coordniate of the location pin",
      minimum: -180,
      maximum: 180,
    },
    Address: {
      type: "string",
      description: "Location address",
    },
    Generic1: {
      type: "number",
      description: "Rating of the first generic rating for the given category",
      minimum: 0,
      maximum: 5,
    },
    Generic2: {
      type: "number",
      description: "Rating of the second generic rating for the given category",
      minimum: 0,
      maximum: 5,
    },
    ImageURL: {
      type: "string",
      description: "URL linking to the images location in blob storage",
    },
    Special: {
      type: "number",
      description:
        "Combined special rating for the given category. It should be the average of the SpecialSans & SpecialStephen ratings",
      minimum: 0,
      maximum: 5,
    },
    SpecialSans: {
      type: "number",
      description: "Sans rating for the special rating of the given category",
      minimum: 0,
      maximum: 5,
    },
    SpecialStephen: {
      type: "number",
      description:
        "Stephens rating for the special rating of the given category",
      minimum: 0,
      maximum: 5,
    },
  },
  required: [
    "PartitionKey",
    "RowKey",
    "Name",
    "Address",
    "SpecialSans",
    "SpecialStephen",
  ],
  additionalProperties: false,
};

module.exports = { categorySchema, locationSchema };
